apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-api.fullname" . }}
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.python.logLevel }}
  REDIS_HOST: {{ include "python-api.fullname" . }}-db
  REDIS_PORT: "6379"