apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api-app.name" . }}
  labels:
    {{- include "python-api.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "python-api.selectorLabels" . | nindent 4 }}
    app: python
  ports:
  - port: 80
    targetPort: api
    name: api
