apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api.fullname" . }}-app
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  selector:
    app: python
    {{- include "python-api.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: api
    name: api
  type: ClusterIP
