apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "python-api.fullname" . }}-python"
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.python.replicas }}
  selector:
    matchLabels:
      app: python-api
      {{- include "python-api.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: python-api
        {{- include "python-api.labels" . | nindent 8 }}
    spec:
      containers:
      - name: python-api
        image: "{{ .Values.python.image.repository }}:{{ .Values.python.image.tag }}"
        imagePullPolicy: {{ .Values.python.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.python.resource.requests.cpu }}
            memory: {{ .Values.python.resource.requests.ram }}
          limits:
            cpu: {{ .Values.python.resource.limits.cpu }}
            memory: {{ .Values.python.resource.limits.ram }}
        ports:
        - containerPort: 5002
          name: api
        envFrom:
          - configMapRef:
              name: {{ include "python-api.fullname" . }}
        readinessProbe:
          tcpSocket:
            port: api
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
      {{- if .Values.python.affinity }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - python-api
            topologyKey: "kubernetes.io/hostname"
      {{- end }}