{{- range $name, $schedule := .Values.python.cronJobSchedule }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "python-api.fullname" $ }}-{{ $name }}
  labels:
    {{- include "python-api.labels" $ | nindent 4 }}
  annotations:
    purpose: "cronjob do automatycznego podbijania countera pythona"
spec:
  successfulJobsHistoryLimit: 0
  schedule: {{ default "* * * * *" $schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        {{- include "python-api.labels" $ | nindent 8 }}
    spec:
      template:
        spec:
          containers:
          - name: counter
            image: cmd.cat/curl
            command:
            - curl
            - -XPOST
            - {{ include "python-api.fullname" $ }}-app/api/v1/info
          restartPolicy: Never
{{- end }}