apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-api.fullname" . }}
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.python.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "python-api.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: python
        {{- include "python-api.labels" . | nindent 8 }}
    spec:
      {{- if .Values.python.affinity }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - python
            topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if .Values.python.tsc }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: python
            {{- include "python-api.selectorLabels" . | nindent 12 }}
      {{- end }}
      enableServiceLinks: false
      containers:
      - name: python-api
        image: {{ with .Values.registry }}{{ . }}/{{ end }}{{ .Values.python.image.name }}:{{ .Values.python.image.tag }}
        resources: {}
        ports:
          - containerPort: 5002
            name: api
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
        readinessProbe:
          tcpSocket:
            port: api
        envFrom:
          - configMapRef:
              name: {{ include "python-api.fullname" . }}
        resources:
          {{- toYaml .Values.python.resources | nindent 10 }}
