apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api.fullname" . }}-python
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  selector:
    app: python-api
    {{- include "python-api.labels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: api
