apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-api-app.name" . }}
  labels:
    {{- include "python-api.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.python.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "python-api.selectorLabels" . | nindent 6 }}
      app: python
  template:
    metadata:
      labels:
        app: python
        {{- include "python-api.labels" $ | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
      - name: python-api
        image: "{{- with .Values.registry }}{{ . }}/{{- end }}{{ .Values.python.image}}:{{ .Values.python.tag }}"
        resources:
          requests:
            cpu: {{ .Values.python.resources.requests.cpu }}
            memory: {{ .Values.python.resources.requests.mem }}
          limits:
            cpu: {{ .Values.python.resources.limits.cpu }}
            memory: {{ .Values.python.resources.limits.mem }}            
        ports:
          - containerPort: 5002
            name: api
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
        readinessProbe:
          tcpSocket:
            port: api
        envFrom:
          - configMapRef:
              name: {{ include "python-api.fullname" . }}
      {{- if .Values.python.affinity }}    
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - python
              topologyKey: kubernetes.io/hostname
      {{- end }}