apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-api.fullname" . }}
  labels:
   {{- include "python-api.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ include "python-api-redis.name" . }}
  REDIS_PORT: "6379"
  LOG_LEVEL: {{ .Values.python.logLevel }}