apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "python-api.fullname" . }}
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "python-api.fullname" . }}-db
  selector:
    matchLabels:
      app: redis
      {{- include "python-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
        {{- include "python-api.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000                   
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: redis
        image: redis:alpine
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 1000
        resources: {}
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
        readinessProbe:
          tcpSocket:
            port: 6379
        volumeMounts:
          - mountPath: /data
            name: {{ include "python-api.fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "python-api.fullname" . }}
      labels:
        {{- include "python-api.labels" . | nindent 8 }}
    spec:
      {{- with .Values.redis.pvc.storageClassName }}
      storageClassName: {{ . }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.redis.pvc.size }}
      accessModes:
        - ReadWriteOnce
