apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-api.fullname" . }}-redis
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
      {{- include "python-api.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
        {{- include "python-api.labels" . | nindent 8 }}
    spec:
      containers:
      - name: redis
        image: "redis:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.redis.resource.requests.cpu }}
            memory: {{ .Values.redis.resource.requests.ram }}
          limits:
            cpu: {{ .Values.redis.resource.limits.cpu }}
            memory: {{ .Values.redis.resource.limits.ram }}
        ports:
        - containerPort: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
        volumeMounts:
        - mountPath: /data
          name: pvc-volume
      volumes:
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: {{ include "python-api.fullname" . }}