apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "python-api.fullname" . }}
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
{{- if ((.Values.redis.pvc).storageClassName) }}
  storageClassName: {{ .Values.redis.pvc.storageClassName }}
{{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}