apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api-redis.name" . }}
  labels:
    {{- include "python-api.labels" $ | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "python-api.selectorLabels" . | nindent 4 }}
    app: redis
  ports:
  - port: 6379
