apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api.fullname" . }}-db
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: redis
    {{- include "python-api.selectorLabels" . | nindent 4 }}
  ports:
  - port: 6379
