registry: 

python:
  logLevel: INFO
  cronJobSchedule: 
    cron1: "* * * * *"
    cron2: "*/2 * * * *"
  replicas: 1
  tsc: false
  affinity: false
  image:
    name: krajewskim/python-api
    tag: new
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  ingressClassName: nginx
  host: api.127.0.0.1.nip.io

redis:
  pvc:
    size: 10Mi
    storageClassName: