registry:
nameOverride:
fullnameOverride:
python:
  logLevel: INFO
  replicas: 1
  image: krajewskim/python-api
  tag: new
  resources:
    requests:
      cpu: 0.1
      mem: 100Mi
    limits:
      cpu: 1
      mem: 250Mi
  affinity: false

cronjobs:
  cronjob1: "* * * * *"
  cronjob2: "*/2 * * * *"

ingress:
  ingressClassName: nginx
  host: api.127.0.0.1.nip.io

redis:
  storageClassName:
  size: 10Mi
  resources:
    requests:
      cpu: 0.1
      mem: 100Mi
    limits:
      cpu: 1
      mem: 250Mi

